### PR TITLE
Some changes.

### PR DESCRIPTION
**Pull request by selectee**
Remove unnecessary code.

### CODE REVIEW

**Comment by selectee** [comment]
Could you please describe your decision to close this PR?

**Comment by yuliskov** [comment]
Wrong branch

Regards, Yuriy

**Comment by selectee** [comment]
But this repo contains only one branch `master`. Which branch to use?

**Comment by yuliskov** [comment]
Sorry, this branch is closed for pull requests

**Comment by yuliskov** [comment]
Please do pull requests to the 'experiments' branch

**Pull request closed without merging**
